version: 1.0.{build}
cache: build64\install
environment:
  APPVEYOR_CACHE_SKIP_SAVE: true
build_script:
- cmd: >-
    C:\msys64\usr\bin\pacman -S base-devel cmake gcc yasm git mercurial subversion gyp tar gmp-devel mpc-devel mpfr-devel python zlib-devel unzip zip --noconfirm --needed

    C:\msys64\usr\bin\bash -lc "cd \"$APPVEYOR_BUILD_FOLDER\" && exec ./build-deps.sh"

    C:\msys64\usr\bin\bash -lc "cd \"$APPVEYOR_BUILD_FOLDER\" && exec ./build-mpv.sh"

    7z a mpv.7z .\build64\mpv-x86_64*\*

    appveyor PushArtifact mpv.7z

    7z a mpv-dev.7z .\build64\mpv-dev-x86_64*\*

    appveyor PushArtifact mpv-dev.7z

    7z a mpv-debug.7z .\build64\mpv-debug-x86_64*\*

    appveyor PushArtifact mpv-debug.7z

    7z a log.7z *.log -r

    7z a log.7z *.cmake -r

    appveyor PushArtifact log.7z
test: off
