version: toolchain-build{build}
build_script:
- cmd: >-
    C:\msys64\usr\bin\pacman -S base-devel cmake gcc yasm git mercurial subversion gyp tar gmp-devel mpc-devel mpfr-devel python2 python2-pip python3 python3-pip zlib-devel unzip zip --noconfirm --needed --noprogressbar --ask 20

    C:\msys64\usr\bin\bash -lc "cd \"$APPVEYOR_BUILD_FOLDER\" && exec ./build-deps.sh"

    C:\msys64\usr\bin\bash -lc "cd \"$APPVEYOR_BUILD_FOLDER\" && exec ./build-gcc.sh"

    7z a toolchain.7z .\build64\install\*

    7z a log.7z *.log *.cmake *.ninja -r
test: off
artifacts:
- path: toolchain.7z
- path: log.7z
on_failure:
- appveyor PushArtifact log.7z
skip_commits:
  files:
    - 'LICENSE'
    - '*.md'
    - '.gitingore'
