version: 0.29.0-build{build}
skip_tags: true
image: Ubuntu1804
build_script:
- sh:  ./appveyor-ubuntu.sh
test: off
artifacts:
- path: mpv.7z
- path: mpv-dev.7z
- path: mpv-debug.7z
- path: log.7z
- path: VERSION
on_failure:
- appveyor PushArtifact log.7z
skip_commits:
  files:
    - 'LICENSE'
    - '*.md'
    - '.gitingore'
environment:
  GITHUB_TOKEN:
    secure: omnW0PL9kWxFUH/igxDUaOAW/JA3dybajD4IJl2ddj+55Nk1M/0YsJa+QWYInQtZ