version: 0.29.0-build{build}
skip_tags: true
image: Ubuntu1804
build_script:
- sh: ./appveyor-ubuntu.sh
test: off
on_failure:
- 7z a -mx9 -r logs.7z *.log *.cmake *.ninja *.txt
- appveyor PushArtifact log.7z
skip_commits:
  files:
    - 'LICENSE'
    - '*.md'
    - '.gitingore'
environment:
  GITHUB_TOKEN:
    secure: omnW0PL9kWxFUH/igxDUaOAW/JA3dybajD4IJl2ddj+55Nk1M/0YsJa+QWYInQtZ